[2023-04-14 17:05:11,058] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-04-14T17:05:09.939789+00:00 [queued]>
[2023-04-14 17:05:11,065] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-04-14T17:05:09.939789+00:00 [queued]>
[2023-04-14 17:05:11,066] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 17:05:11,067] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-04-14 17:05:11,067] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 17:05:11,076] {taskinstance.py:1397} INFO - Executing <Task(ReadScopus): get_scopus_data> on 2023-04-14 17:05:09.939789+00:00
[2023-04-14 17:05:11,082] {standard_task_runner.py:52} INFO - Started process 423 to run task
[2023-04-14 17:05:11,086] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'vic_investigacion_ETL', 'get_scopus_data', 'manual__2023-04-14T17:05:09.939789+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/vic_investigacion_dag.py', '--cfg-path', '/tmp/tmp3d68c8iy', '--error-file', '/tmp/tmpmi2ipxhu']
[2023-04-14 17:05:11,090] {standard_task_runner.py:80} INFO - Job 90: Subtask get_scopus_data
[2023-04-14 17:05:11,181] {task_command.py:371} INFO - Running <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-04-14T17:05:09.939789+00:00 [running]> on host d014c8b814c7
[2023-04-14 17:05:11,251] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vic_investigacion_ETL
AIRFLOW_CTX_TASK_ID=get_scopus_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T17:05:09.939789+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-14T17:05:09.939789+00:00
[2023-04-14 17:05:11,252] {logging_mixin.py:115} INFO - Getting Scopus Data
[2023-04-14 17:05:11,253] {logging_mixin.py:115} INFO - The api key is:  640ababb3eaaa3723c7cc11be848250b
[2023-04-14 17:05:11,254] {logging_mixin.py:115} INFO - READIINGGGGGGGGGGG!!!!
[2023-04-14 17:05:11,254] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/read_scopus_operator.py", line 28, in execute
    self.saveData()
  File "/opt/airflow/dags/read_scopus_operator.py", line 32, in saveData
    file_path = os.path.join(os.environ.get("DAGS_FOLDER"), "my_file.txt")
  File "/usr/local/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-04-14 17:05:11,265] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=vic_investigacion_ETL, task_id=get_scopus_data, execution_date=20230414T170509, start_date=20230414T170511, end_date=20230414T170511
[2023-04-14 17:05:11,271] {standard_task_runner.py:97} ERROR - Failed to execute job 90 for task get_scopus_data (expected str, bytes or os.PathLike object, not NoneType; 423)
[2023-04-14 17:05:11,299] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-14 17:05:11,332] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
