[2023-06-01 02:00:15,479] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-06-01T02:00:12.246287+00:00 [queued]>
[2023-06-01 02:00:15,499] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-06-01T02:00:12.246287+00:00 [queued]>
[2023-06-01 02:00:15,500] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-01 02:00:15,502] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-06-01 02:00:15,504] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-01 02:00:15,528] {taskinstance.py:1397} INFO - Executing <Task(ReadScopus): get_scopus_data> on 2023-06-01 02:00:12.246287+00:00
[2023-06-01 02:00:15,544] {standard_task_runner.py:52} INFO - Started process 4734 to run task
[2023-06-01 02:00:15,559] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'vic_investigacion_ETL', 'get_scopus_data', 'manual__2023-06-01T02:00:12.246287+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/vic_investigacion_dag.py', '--cfg-path', '/tmp/tmpmnmt94as', '--error-file', '/tmp/tmp79qookwn']
[2023-06-01 02:00:15,572] {standard_task_runner.py:80} INFO - Job 193: Subtask get_scopus_data
[2023-06-01 02:00:15,712] {task_command.py:371} INFO - Running <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-06-01T02:00:12.246287+00:00 [running]> on host 5d9ccb732815
[2023-06-01 02:00:15,801] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vic_investigacion_ETL
AIRFLOW_CTX_TASK_ID=get_scopus_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-01T02:00:12.246287+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-01T02:00:12.246287+00:00
[2023-06-01 02:00:15,804] {logging_mixin.py:115} INFO - Getting Scopus Data
[2023-06-01 02:00:15,813] {logging_mixin.py:115} INFO - The api key is:  640ababb3eaaa3723c7cc11be848250b
[2023-06-01 02:00:15,815] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/read_scopus_operator.py", line 29, in execute
    self.saveData()
TypeError: saveData() missing 1 required positional argument: 'authors_list_data'
[2023-06-01 02:00:15,833] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=vic_investigacion_ETL, task_id=get_scopus_data, execution_date=20230601T020012, start_date=20230601T020015, end_date=20230601T020015
[2023-06-01 02:00:15,856] {standard_task_runner.py:97} ERROR - Failed to execute job 193 for task get_scopus_data (saveData() missing 1 required positional argument: 'authors_list_data'; 4734)
[2023-06-01 02:00:15,908] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-01 02:00:15,971] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
