[2023-06-01 01:59:01,920] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-06-01T01:58:59.752934+00:00 [queued]>
[2023-06-01 01:59:01,933] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-06-01T01:58:59.752934+00:00 [queued]>
[2023-06-01 01:59:01,934] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-01 01:59:01,935] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-06-01 01:59:01,936] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-01 01:59:01,949] {taskinstance.py:1397} INFO - Executing <Task(ReadScopus): get_scopus_data> on 2023-06-01 01:58:59.752934+00:00
[2023-06-01 01:59:01,958] {standard_task_runner.py:52} INFO - Started process 4642 to run task
[2023-06-01 01:59:01,964] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'vic_investigacion_ETL', 'get_scopus_data', 'manual__2023-06-01T01:58:59.752934+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/vic_investigacion_dag.py', '--cfg-path', '/tmp/tmpli_3zo_a', '--error-file', '/tmp/tmp24p0bpdt']
[2023-06-01 01:59:01,967] {standard_task_runner.py:80} INFO - Job 184: Subtask get_scopus_data
[2023-06-01 01:59:02,129] {task_command.py:371} INFO - Running <TaskInstance: vic_investigacion_ETL.get_scopus_data manual__2023-06-01T01:58:59.752934+00:00 [running]> on host 5d9ccb732815
[2023-06-01 01:59:02,211] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vic_investigacion_ETL
AIRFLOW_CTX_TASK_ID=get_scopus_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-01T01:58:59.752934+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-01T01:58:59.752934+00:00
[2023-06-01 01:59:02,213] {logging_mixin.py:115} INFO - Getting Scopus Data
[2023-06-01 01:59:02,214] {logging_mixin.py:115} INFO - The api key is:  640ababb3eaaa3723c7cc11be848250b
[2023-06-01 01:59:02,216] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/read_scopus_operator.py", line 29, in execute
    self.saveData()
TypeError: saveData() missing 1 required positional argument: 'authors_data'
[2023-06-01 01:59:02,228] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=vic_investigacion_ETL, task_id=get_scopus_data, execution_date=20230601T015859, start_date=20230601T015901, end_date=20230601T015902
[2023-06-01 01:59:02,245] {standard_task_runner.py:97} ERROR - Failed to execute job 184 for task get_scopus_data (saveData() missing 1 required positional argument: 'authors_data'; 4642)
[2023-06-01 01:59:02,310] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-01 01:59:02,345] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
